// const cardItems = [
//   {
//     id: 1,
//     name: "Classic Burger",
//     description: "Juicy beef patty with lettuce, tomato, and special sauce",
//     price: "9.99",
//     imageUrl: "/Images/ClassicBurger.avif",
//     category: "Burgers",
//   },
//   {
//     id: 2,
//     name: "Crispy Fries",
//     description: "Golden crispy fries with sea salt",
//     price: "4.99",
//     imageUrl: "/Images/CrispyFries.jpg",
//     category: "Sides",
//   },
//   {
//     id: 3,
//     name: "Chicken Wings",
//     description: "Spicy buffalo wings with blue cheese dip",
//     price: "12.99",
//     imageUrl: "/Images/ChickenWings.jpg",
//     category: "Appetizers",
//   },
//   {
//     id: 4,
//     name: "Caesar Salad",
//     description: "Fresh romaine with parmesan and croutons",
//     price: "8.99",
//     imageUrl: "/Images/CaesarSalad.jpg",
//     category: "Salads",
//   },
//   {
//     id: 5,
//     name: "Milkshake",
//     description: "Creamy vanilla milkshake with whipped cream",
//     price: "5.99",
//     imageUrl: "https://images.unsplash.com/photo-1485963631004-f2f00b1d6606",
//     category: "Drinks",
//   },
//   {
//     id: 6,
//     name: "Pizza Slice",
//     description: "Fresh mozzarella and basil pizza slice",
//     price: "3.99",
//     imageUrl: "https://images.unsplash.com/photo-1504754524776-8f4f37790ca0",
//     category: "Pizza",
//   },
//   {
//     id: 7,
//     name: "Double Cheeseburger",
//     description: "Two juicy beef patties with melted cheese, lettuce, and special sauce",
//     price: "12.99",
//     imageUrl: "/Images/DoubleCheeseburger.jpg",
//     category: "Burgers",
//   },
//   {
//     id: 8,
//     name: "Onion Rings",
//     description: "Crispy battered onion rings served with a tangy dip",
//     price: "5.99",
//     imageUrl: "/Images/OnionRings.jpg",
//     category: "Sides",
//   },
//   {
//     id: 9,
//     name: "BBQ Chicken Wings",
//     description: "Smoky BBQ-glazed wings served with ranch dressing",
//     price: "13.99",
//     imageUrl: "/Images/BBQChicken.jpg",
//     category: "Appetizers",
//   },
//   {
//     id: 10,
//     name: "Greek Salad",
//     description: "Fresh cucumbers, tomatoes, feta cheese, and olives with Greek dressing",
//     price: "9.49",
//     imageUrl: "Images/GreekSalad.jpg",
//     category: "Salads",
//   },
//   {
//     id: 11,
//     name: "Chocolate Shake",
//     description: "Rich chocolate milkshake topped with whipped cream and chocolate syrup",
//     price: "6.49",
//     imageUrl: "/Images/ChocolateShake.avif",
//     category: "Drinks",
//   },
//   {
//     id: 12,
//     name: "Pepperoni Pizza",
//     description: "Classic pepperoni pizza with a crispy crust and melted cheese",
//     price: "10.99",
//     imageUrl: "/Images/PepperoniPizza.jpg",
//     category: "Pizza",
//   },
//   {
//     id: 13,
//     name: "Grilled Chicken Sandwich",
//     description: "Grilled chicken breast with lettuce, tomato, and mayo on a brioche bun",
//     price: "8.99",
//     imageUrl: "https://images.unsplash.com/photo-1550547660-d9450f859349",
//     category: "Burgers",
//   },
//   {
//     id: 14,
//     name: "Mozzarella Sticks",
//     description: "Crispy mozzarella sticks served with marinara sauce",
//     price: "7.49",
//     imageUrl: "/Images/MozzarellaSticks.jpg",
//     category: "Appetizers",
//   },
//   {
//     id: 15,
//     name: "Garlic Bread",
//     description: "Toasted garlic bread with butter and herbs",
//     price: "4.49",
//     imageUrl: "/Images/GarlicBread.avif",
//     category: "Sides",
//   },
//   {
//     id: 16,
//     name: "Iced Coffee",
//     description: "Cold brewed coffee with a hint of vanilla and ice",
//     price: "3.99",
//     imageUrl: "/Images/IcedCoffee.avif",
//     category: "Drinks",
//   },
//   {
//     id: 17,
//     name: "Spaghetti Bolognese",
//     description: "Classic spaghetti with rich meat sauce and parmesan cheese",
//     price: "11.99",
//     imageUrl: "/Images/SpaghettiBolognese.jpg",
//     category: "Pasta",
//   },
//   {
//     id: 18,
//     name: "Strawberry Smoothie",
//     description: "Refreshing strawberry smoothie with yogurt and honey",
//     price: "5.99",
//     imageUrl: "/Images/StrawberrySmoothie.avif",
//     category: "Drinks",
//   },
//   {
//     id: 19,
//     name: "Mango Lassi",
//     description: "Delicious mango lassi with fresh mangoes and yogurt",
//     price: "4.99",
//     imageUrl: "/Images/mangolassi.jpg",
//     // imageUrl: "https://source.unsplash.com/400x300/?mango,lassi",

//     category: "Drinks",
//   },
//   {
//     id: 20,
//     name: "Blueberry Shake",
//     description: "Creamy blueberry shake with vanilla and honey",
//     price: "6.49",
//     imageUrl: "https://images.unsplash.com/photo-1563805042-7684c019e1cb",
//     category: "Drinks",
//   }
  
// ];

// export default cardItems;
